version: 2
updates:
  # Frontend dependencies (pnpm)
  - package-ecosystem: "npm"
    directory: "/fe"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 10
    labels:
      - "pnpm-dependencies"
    # 自动合并 minor 和 patch 更新
    ignore:
      # Ignore major version updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    automerge: true

  # Android dependencies (Gradle)
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 10
    labels:
      - "gradle-dependencies"
    # 自动合并 minor 和 patch 更新
    ignore:
      # Ignore major version updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    automerge: true