version: 2
updates:
  # Frontend dependencies (pnpm)
  - package-ecosystem: "npm"
    directory: "/fe"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 10
    labels:
      - "pnpm-dependencies"

  # Android dependencies (Gradle)
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 10
    labels:
      - "gradle-dependencies"