name: Android Tests

on:
  push:
    paths:
      - 'android/**'
  pull_request:
    paths:
      - 'android/**'
  workflow_dispatch:

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Grant execute permission for gradlew
        run: chmod +x ./android/gradlew
        
      - name: Run unit tests
        working-directory: ./android
        run: ./gradlew testDebugUnitTest --no-daemon --parallel
        
      - name: Upload unit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: ./android/app/build/reports/tests/testDebugUnitTest
          retention-days: 5
