name: Android Tests

on:
  push:
    paths:
      - 'android/**'
  pull_request:
    paths:
      - 'android/**'
  workflow_dispatch:

jobs:
  test:
    name: Run Android Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Android SDK
      uses: actions/cache@v4
      with:
        path: |
          ~/.android/avd
          ~/.android/adb*
          ~/android-sdk
          ~/.android/sdk
        key: ${{ runner.os }}-android-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-android-
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Setup emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        arch: x86_64
        profile: Nexus 6
        disable-animations: true
        script: |
          echo "Waiting for device to be ready..."
          adb wait-for-device
          echo "Device is ready"
          adb devices
          # Wait for boot to complete
          adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'
          # Disable animations
          adb shell settings put global window_animation_scale 0.0
          adb shell settings put global transition_animation_scale 0.0
          adb shell settings put global animator_duration_scale 0.0
          echo "Emulator is ready"
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      working-directory: ./android
      
    - name: Run unit tests
      working-directory: ./android
      run: ./gradlew test
      
    - name: Verify emulator is ready
      working-directory: ./android
      run: |
        adb wait-for-device
        adb shell getprop sys.boot_completed | grep -q 1
        
    - name: Run instrumentation tests
      working-directory: ./android
      run: |
        ./gradlew connectedDebugAndroidTest
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: android/**/build/reports/tests/
        retention-days: 7
